version: 0.2
env:
  variables:
    S3_BUCKET: "{{S3_BUCKET_URL}}"
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build Started
      - ng build
artifacts:
  files:
      - '**/*'
  base-directory: 'dist*'
  discard-paths: yes